name: Sunbird Frontend Test Suite and Linting
on:
  push:
    branches:
      - "**"

jobs:
  linting-and-formatting:
    name: Linting and Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # Install project dependencies
      - run: npm ci

      # Lint with ESLint
      - name: Lint with ESLint
        run: npm run lint

      # Run tests with Jest (optional)
      # - name: Run Tests
      #   run: npm test
